config/routes.rb
Rails.application.routes.draw do
  resources :agents
  resources :comments
  resources :tickets
  resources :users, only: [:index, :create, :show]
  post 'users/email', to: 'users#email'
  post 'login', to: 'auth#login'
  get '/translations', to: 'translations#index'
  get '/search', to: 'search#search'
end

app/models/agent.rb
class Agent < ApplicationRecord
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: %i[ show edit update destroy ]

  # GET /agents or /agents.json
  def index
    @agents = Agent.all
    render json: @agents
  end

  # GET /agents/1 or /agents/1.json
  def show
    @agent = Agent.find(params[:id])
    render json: @agent
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents or /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.json { render :show, status: :created, location: @agent }
      else
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1 or /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to agent_url(@agent), notice: "Agent was successfully updated." }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1 or /agents/1.json
  def destroy
    @agent.destroy

    respond_to do |format|
      format.json { render :show, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agent_params
      params.require(:agent).permit(:name, :user_name, :email, :team, :profile_pic, :phone_number)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_form.html.erb
<%= form_with(model: agent, local: true) do |form| %>
  <% if agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team %>
  </div>

  <div class="field">
    <%= form.label :profile_pic %>
    <%= form.text_field :profile_pic %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User name</th>
      <th>Email</th>
      <th>Team</th>
      <th>Profile pic</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.name %></td>
        <td><%= agent.user_name %></td>
        <td><%= agent.email %></td>
        <td><%= agent.team %></td>
        <td><%= agent.profile_pic %></td>
        <td><%= agent.phone_number %></td>
        <td><%= link_to 'Show', agent %></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>

<p>
  <strong>User name:</strong>
  <%= @agent.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agent.email %>
</p>

<p>
  <strong>Team:</strong>
  <%= @agent.team %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= @agent.profile_pic %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @agent.phone_number %>
</p>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>