config/routes.rb
Rails.application.routes.draw do
  resources :agents
  resources :comments
  resources :tickets
  resources :users, only: [:index, :create, :show]
  post 'users/email', to: 'users#email'
  post 'login', to: 'auth#login'
  get '/translations', to: 'translations#index'
  get '/search', to: 'search#search'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :comments, dependent: :destroy
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks


  after_commit :index_document, on: %i[create update]
  after_commit :delete_document, on: :destroy

  # Define methods for Elasticsearch search queries
  def self.search(query)
    puts query
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            type: 'phrase_prefix'
          }
        }
      }
    )
  end

  private
  def index_document
    __elasticsearch__.index_document
  end

  def delete_document
    __elasticsearch__.delete_document
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
    render json: @tickets
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    @ticket = Ticket.includes(:comments).find(params[:id])
    render json: @ticket, include: 'comments'
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        assign_ticket(@ticket)
        format.json { render :show, status: :created, location: @ticket }
      else
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        render :show, status: :ok, location: @ticket
      else
        render json: @ticket.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      render :show, status: :ok
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :createdby, :modifiedby, :status, :assigned_to_user, :assigned_to_user_id)
    end

  def assign_ticket(ticket)
    # Names of the agents
    agent_names = ["Agent1", "Agent2"]

    # Calculate the index of the agent to assign the ticket to based on the ticket ID
    agent_index = ticket.id % agent_names.length

    # Assign the agent name to the agent_id attribute of the ticket record
    agent_name = agent_names[agent_index]
    ticket.update(assigned_to_user: agent_name, assigned_to_user_id: agent_index)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments %>
  </div>

  <div class="field">
    <%= form.label :createdby %>
    <%= form.text_field :createdby %>
  </div>

  <div class="field">
    <%= form.label :modifiedby %>
    <%= form.text_field :modifiedby %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :assigned_to_user %>
    <%= form.text_field :assigned_to_user %>
  </div>

  <div class="field">
    <%= form.label :assigned_to_user_id %>
    <%= form.number_field :assigned_to_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Comments</th>
      <th>Createdby</th>
      <th>Modifiedby</th>
      <th>Status</th>
      <th>Assigned to user</th>
      <th>Assigned to user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.comments %></td>
        <td><%= ticket.createdby %></td>
        <td><%= ticket.modifiedby %></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.assigned_to_user %></td>
        <td><%= ticket.assigned_to_user_id %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @ticket.comments %>
</p>

<p>
  <strong>Createdby:</strong>
  <%= @ticket.createdby %>
</p>

<p>
  <strong>Modifiedby:</strong>
  <%= @ticket.modifiedby %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Assigned to user:</strong>
  <%= @ticket.assigned_to_user %>
</p>

<p>
  <strong>Assigned to user:</strong>
  <%= @ticket.assigned_to_user_id %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>